"""Initial migration

Revision ID: 7fcdf97992d2
Revises: 
Create Date: 2026-03-11 00:23:18.664285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcdf97992d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_providers_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_deleted_at', 'providers', ['deleted_at'], unique=False)
    op.create_index('ux_providers_name_active', 'providers', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(display_name)) > 0', name='ck_users_display_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ux_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('icon_name', sa.String(length=100), server_default='Savings', nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('include_in_total', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'", name='ck_accounts_color_hex'),
    sa.CheckConstraint("currency_code ~ '^[A-Z]{3}$'", name='ck_accounts_currency_iso4217'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_accounts_name_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_user_archived_deleted', 'accounts', ['user_id', 'is_archived', 'deleted_at'], unique=False)
    op.create_index('ix_accounts_user_include_total_deleted', 'accounts', ['user_id', 'include_in_total', 'deleted_at'], unique=False)
    op.create_index('ux_accounts_user_name_active', 'accounts', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('is_system_category', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('icon_name', sa.String(length=100), server_default='Savings', nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category_type IN ('expense', 'income')", name='ck_categories_category_type'),
    sa.CheckConstraint("color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'", name='ck_categories_color_hex'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_categories_name_not_empty'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_categories_parent_not_self'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_user_parent_deleted', 'categories', ['user_id', 'parent_id', 'deleted_at'], unique=False)
    op.create_index('ix_categories_user_type_deleted', 'categories', ['user_id', 'category_type', 'deleted_at'], unique=False)
    op.create_index('ux_categories_user_parent_name_type_active', 'categories', ['user_id', 'parent_id', 'name', 'category_type'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('provided_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(provider_user_id)) > 0', name='ck_provided_users_provider_user_not_empty'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provided_users_provider_deleted', 'provided_users', ['provider_id', 'deleted_at'], unique=False)
    op.create_index('ix_provided_users_user_deleted', 'provided_users', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ux_provided_users_provider_user_active', 'provided_users', ['provider_id', 'provider_user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(transaction_type = 'income' AND destination_account_id IS NOT NULL AND source_account_id IS NULL AND category_id IS NOT NULL) OR (transaction_type = 'expense' AND source_account_id IS NOT NULL AND destination_account_id IS NULL AND category_id IS NOT NULL) OR (transaction_type = 'transfer' AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL AND source_account_id <> destination_account_id AND category_id IS NULL AND target_amount IS NOT NULL)", name='ck_transactions_type_integrity'),
    sa.CheckConstraint("transaction_type IN ('income', 'expense', 'transfer', 'overwrite')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_destination_occurred', 'transactions', ['destination_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_transactions_source_occurred', 'transactions', ['source_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_transactions_user_occurred_deleted', 'transactions', ['user_id', 'occurred_at', 'deleted_at'], unique=False)
    op.create_index('ix_transactions_user_type_occurred_deleted', 'transactions', ['user_id', 'transaction_type', 'occurred_at', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_type_occurred_deleted', table_name='transactions')
    op.drop_index('ix_transactions_user_occurred_deleted', table_name='transactions')
    op.drop_index('ix_transactions_source_occurred', table_name='transactions')
    op.drop_index('ix_transactions_destination_occurred', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ux_provided_users_provider_user_active', table_name='provided_users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_provided_users_user_deleted', table_name='provided_users')
    op.drop_index('ix_provided_users_provider_deleted', table_name='provided_users')
    op.drop_table('provided_users')
    op.drop_index('ux_categories_user_parent_name_type_active', table_name='categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_categories_user_type_deleted', table_name='categories')
    op.drop_index('ix_categories_user_parent_deleted', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ux_accounts_user_name_active', table_name='accounts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_accounts_user_include_total_deleted', table_name='accounts')
    op.drop_index('ix_accounts_user_archived_deleted', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ux_users_email_active', table_name='users', postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_users_updated_at', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ux_providers_name_active', table_name='providers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_providers_deleted_at', table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
