/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as CategoriesNewRouteImport } from './routes/categories/new'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/register'
    | '/settings'
    | '/accounts/new'
    | '/categories/new'
    | '/transactions/new'
    | '/accounts/'
    | '/categories/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/register'
    | '/settings'
    | '/accounts/new'
    | '/categories/new'
    | '/transactions/new'
    | '/accounts'
    | '/categories'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/dashboard'
    | '/register'
    | '/settings'
    | '/accounts/new'
    | '/categories/new'
    | '/transactions/new'
    | '/accounts/'
    | '/categories/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AccountsNewRoute: typeof AccountsNewRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AccountsNewRoute: AccountsNewRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
